In [3]:
import torch

def part1():

    print("--- part 1: TENSOR stuff  ---")

    # a single number
    scalar = torch.tensor(42)
    print(f"SCALAR:\n{scalar} (shape: {scalar.shape}, dim: {scalar.ndim})")


    # a list of numbers
    vector = torch.tensor([1, 2, 3])
    print(f"vector:\n{vector} (shape: {vector.shape}, dim: {vector.ndim})")

    # a table of numbers
    matrix = torch.tensor([[5, 10],
                           [15, 20]])
    print(f"mATRIx:\n{matrix} (shape: {matrix.shape}, dim: {matrix.ndim})")

    # BIG data (like an image)
    tensor_3d = torch.tensor([[[1, 2],
                               [3, 4]]])
    print(f"3D tensor is just a:\n{tensor_3d} (shape: {tensor_3d.shape}, dim: {tensor_3d.ndim})")

    print("\n" + "="*40 + "\n")


def part2():
    print("--- part 2: doing MATHS on tensors ---")

    # regular math
    x = torch.tensor([1, 2, 3])

    print(f"Orig:\n {x}")
    print(f"Add 10: {x + 10}")
    print(f"TIMES self: {x * x}")

    # matrix multiplication (MUST do this for NN's)
    A = torch.tensor([[1, 2],
                      [3, 4]])
    B = torch.tensor([[5, 6],
                      [7, 8]])

    # (2, 2) times (2, 2) makes (2, 2)
    C = torch.matmul(A, B)
    print(f"\nMat mul A ({A.shape}) @ B ({B.shape}):\n{C} (shape: {C.shape})")



    # this is how you FIX a SHAPE error
    D = torch.tensor([[1, 2],
                      [3, 4],
                      [5, 6]])
    E = torch.tensor([[7, 8, 9],
                      [10, 11, 12]])

    # D is (3, 2), E is (2, 3). inner are the same (2), so it works
    F = torch.matmul(D, E)
    print(f"\nMat mul D ({D.shape}) @ E ({E.shape}):\n{F} (shape: {F.shape})")
    print("\n" + "="*40 + "\n")



def part3():
    print("--- part 3: changing the shape and TRANSFERS ---")

    # add a dimension (used for adding a batch size of 1)
    x = torch.rand(3, 224, 224) # just a rando image
    print(f"Original shappe: {x.shape}")

    # add a dimension at the start (dim=0)
    x_batch = torch.unsqueeze(x, dim=0)
    print(f"After unsqueez: {x_batch.shape}")


    # remove dimensions of size 1 (clean up messy outputs)
    z = torch.rand(1, 10, 1) # rando model output
    print(f"\nMessy output shape: {z.shape}")

    z_clean = torch.squeeze(z)
    print(f"After squeese: {z_clean.shape}")


    # changing the shape (view) - important for LINEAR layers
    tensor_to_flatten = torch.arange(12).reshape(3, 4)
    print(f"\nOriginal TENSORS to flatten:\n{tensor_to_flatten}")

    # -1 means 'figure out the size yourself'
    flattened = tensor_to_flatten.view(-1)
    print(f"totally FLATTENED:\n{flattened} (shape: {flattened.shape})")

    # keep 3 rows, but flatten the collums for the linear layr
    flattened_linear = tensor_to_flatten.view(3, -1)
    print(f"Flattened for linar:\n{flattened_linear} (shape: {flattened_linear.shape})")
    print("\n" + "="*40 + "\n")


if __name__ == "__main__":
    part1()
    part2()
    part3()

--- part 1: TENSOR stuff  ---
SCALAR:
42 (shape: torch.Size([]), dim: 0)
vector:
tensor([1, 2, 3]) (shape: torch.Size([3]), dim: 1)
mATRIx:
tensor([[ 5, 10],
        [15, 20]]) (shape: torch.Size([2, 2]), dim: 2)
3D tensor is just a:
tensor([[[1, 2],
         [3, 4]]]) (shape: torch.Size([1, 2, 2]), dim: 3)


--- part 2: doing MATHS on tensors ---
Orig:
 tensor([1, 2, 3])
Add 10: tensor([11, 12, 13])
TIMES self: tensor([1, 4, 9])

Mat mul A (torch.Size([2, 2])) @ B (torch.Size([2, 2])):
tensor([[19, 22],
        [43, 50]]) (shape: torch.Size([2, 2]))

Mat mul D (torch.Size([3, 2])) @ E (torch.Size([2, 3])):
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]]) (shape: torch.Size([3, 3]))


--- part 3: changing the shape and TRANSFERS ---
Original shappe: torch.Size([3, 224, 224])
After unsqueez: torch.Size([1, 3, 224, 224])

Messy output shape: torch.Size([1, 10, 1])
After squeese: torch.Size([10])

Original TENSORS to flatten:
tensor([[ 0,  1,  2,  3],
        [ 